name: Deploy Nuxt To-Do app to GitHub Pages

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.14
      - name: Install dependencies
        run: bun i
      - name: Generate static site
        run: bun generate && touch .output/public/.nojekyll
    
      - name: Pushes ".output/public" folder to "jesusfj710/jesusfj710.github.io" public repo
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        with:
          source-directory: '.output/public'
          destination-repository-name: 'to-do-app'
          destination-github-username: 'jesusfj710'
          user-email: 'jesusfj710@proton.me'
          target-branch: 'main'